### ISSUE TITLE
UI logic

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#1]
after clicking the option "statusbar_*" (string) I changed category. got this - description of old option and selected new option
![op1](https://user-images.githubusercontent.com/4154978/117536310-fadad280-b002-11eb-844d-8a18a6faaba1.png)

**Comment by halfbrained** [comment]
On list update I select the option that was selected before. When the option is not present in new list should I just select the first one?

And when the list is empty should I just hide the whole bottom part? Or maybe clear and disable those widgets, would be nicer?

**Comment by Alexey-T** [comment]
When the option is not present in new list should I just select the first one?— yes

Or maybe clear and disable those widgets, would be nicer?- clear and disable
