### ISSUE TITLE
on default theme, gray color of BG is not the same gray as on Cud tabs+statusbar

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#11]
![Screenshot from 2021-05-09 21-32-18](https://user-images.githubusercontent.com/4154978/117583139-31e9da80-b10e-11eb-89b7-cf9cabb1967d.png)

**Comment by halfbrained** [comment]
Changed to 'TabBg' color. But tree, list and memo look weird with that background

![borderless](https://user-images.githubusercontent.com/74829192/117615706-c554f700-b172-11eb-8ef4-c2728d1e0bb2.png)

Thought I'd add a border, but it seems to use some OS color for it, any way to change that color?

![dark_border](https://user-images.githubusercontent.com/74829192/117615804-ecabc400-b172-11eb-9a89-ec84bb66a818.png)

**Comment by Alexey-T** [comment]
currently no way to colorize the border,,,.
