### ISSUE TITLE
just remind about Kv plugin features which you show in 'help'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#13]
![Screenshot from 2021-05-10 15-13-48](https://user-images.githubusercontent.com/4154978/117657586-67d89e80-b1a2-11eb-9b7f-5ff10758ef6f.png)

**Comment by halfbrained** [comment]
I don't get your meaning, please elaborate

**Comment by Alexey-T** [comment]
- is column ! supporting all values from pic?
- are "<" and ">" supported in filter?
- are ! and !! and !!! supported in filter?
- is # supported in filter?

**Comment by halfbrained** [comment]
All of this is currently still on kvichan's code, so yes - everything is supported
