### ISSUE TITLE
the idea Kv did not implement

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#15]
https://github.com/Alexey-T/CudaText/issues/3047

**Comment by halfbrained** [comment]
Looked through kvichan's code a bit, looks doable

**Comment by halfbrained** [comment]
Added (https://github.com/halfbrained/cuda_prefs/commit/8bed21ae071dbaecaa8246af971115a96c120594)

(In the end decided not to mess with kvichans' code, and did it the easy way :) )
