### ISSUE TITLE
listbox_ex border is themed now

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#16]
1.0.390 (app 1.133.0)
* add: dlg_proc: control "listbox_ex" border is themed now

**Comment by halfbrained** [comment]
Not for me. Downloaded from fosshub

![not_themed_list](https://user-images.githubusercontent.com/74829192/117778585-77112800-b246-11eb-814c-970a026e6044.png)

**Comment by Alexey-T** [comment]
I didn’t check, it was code added but doesn’t work

**Comment by Alexey-T** [comment]
now checked, it's OK now. will be in update

**Comment by Alexey-T** [comment]
proof-- top list

![Screenshot from 2021-05-11 12-50-47](https://user-images.githubusercontent.com/4154978/117796472-cad83d00-b257-11eb-9f4d-c39c2f411d02.png)
