### ISSUE TITLE
default Ubuntu font don't fit in caption

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#18]
![Screenshot from 2021-05-11 13-40-36](https://user-images.githubusercontent.com/4154978/117802784-8dc37900-b25e-11eb-9dd5-55f1e231239e.png)

we can remove word 'dimenstions'

**Comment by halfbrained** [comment]
Ok, added to TODOs

**Comment by halfbrained** [comment]
done ([here](https://github.com/halfbrained/cuda_prefs/commit/763b591762a9f5675b2499e7e065aeb0a8eacac0#diff-9b1a86a9bdabb49a99020e218abd77a007992a7d63071cbbf523e3b6edc210bbR496))
