### ISSUE TITLE
Checkbox is not themed

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#19]
Hi @halfbrained 

Could you check this part?

![image](https://user-images.githubusercontent.com/5806694/118285152-c8175b00-b496-11eb-8a37-c5aad3c478b3.png)

**Comment by halfbrained** [comment]
Huh, works for me. @Alexey-T, thoughts?

![checkbox](https://user-images.githubusercontent.com/74829192/118287682-5b26b400-b4dc-11eb-83d4-5e8640fcbde1.png)

**Comment by Alexey-T** [comment]
checkbox is system (OS) control, I cannot affect its look. only size/ font name+size+color maybe.

**Comment by Alexey-T** [comment]
An idea! button_ex with a custom icon can mimic the checkbox.

**Comment by halfbrained** [comment]
Ok, will move to using 'button_ex'

**Comment by Alexey-T** [comment]
icons are here https://www.iconfinder.com/search/?q=check

**Comment by halfbrained** [comment]
Changed to 'button_ex'

![checkbox_new](https://user-images.githubusercontent.com/74829192/118392274-76f79a80-b641-11eb-9a2b-be26c3ea712d.png)

**Comment by Alexey-T** [comment]
yes, such icons looks OK on light+dark backgnd.

**Comment by Alexey-T** [comment]
but `[X]` icon looks like 'enabled' too!

**Comment by halfbrained** [comment]
Empty?

![cb_2](https://user-images.githubusercontent.com/74829192/118395837-2d18af80-b655-11eb-9702-869eab27b9c9.png)

**Comment by Alexey-T** [comment]
yes-- this is ok.

**Comment by halfbrained** [comment]
updated
