### ISSUE TITLE
Usability: OK or Apply needs to consider the value in textbox without wait for Enter key to accept current value.

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#21]
1. Open Option Editor Lite.
2. Change value for a setting. Don't press Enter.
3. Click on OK button.
4. The new value is ignored.

![image](https://user-images.githubusercontent.com/5806694/118302602-0a966300-b4aa-11eb-892e-84b5de76f8c9.png)

**Comment by JairoMartinezA** [comment]
Additional to this, the requirement is because now the idea is to simulate a common Preferences dialog, I suggest also include a Cancel button like SynWrite, maybe the Close button is doing the same?, but finally the plugin need to consider ignore all the changes, it is because currently we have an Apply button, is just a suggestion 👍 

![image](https://user-images.githubusercontent.com/5806694/118312299-bd6cbe00-b4b6-11eb-8a00-2361721605ff.png)

**Comment by halfbrained** [comment]
There is no consistent behavior for a "Cancel" button, so I want to clarify: "Cancel" is expected to undo applied changes, right?

**Comment by Alexey-T** [comment]
Cancel - can be used only if changes were __not__ applied yet.

**Comment by halfbrained** [comment]
So... just close? :) Should I rename it to 'Cancel'

I thought maybe you'd apply some changes, then cancel (undo applied) them if didn't like the result

**Comment by Alexey-T** [comment]
way1: we have OK (apply + close), Apply(apply), Cancel (don't apply+ close)

way2: we apply on each change

**Comment by Alexey-T** [comment]
>So... just close? :) Should I rename it to 'Cancel'

it will be bad UI, "Close" is ok as now, "Cancel" means different thing (don't apply+close).

**Comment by halfbrained** [comment]
Well I'm confused now. Currently:
* Apply - applies...
* OK - apply and close
* Close - just closes

Is this not as expected?

**Comment by Alexey-T** [comment]
so current dialog applies only on Apply press? not on control changing?
if so, 'Close' shoud be 'Cancel'.
if control changing applies too, then what 'Close'  does ?

**Comment by halfbrained** [comment]
> so current dialog applies only on Apply press? not on control changing?

Yes. On control-change/<Enter>-press I store the changes, and apply all stored changes only when "Apply" or "OK" is pressed; on <Escape> or "Close" - dialog is closed and changes are discarded.

**Comment by Alexey-T** [comment]
then 'Close" should be renamed to 'Cancel', see above.

**Comment by halfbrained** [comment]
'Apply' and 'OK' now apply current edited value without <Enter> (should have thought of this myself :) ); and renamed 'Close' to 'Cancel'. Everything seems to be fixed.

**Comment by Alexey-T** [comment]
hmm. if I edit font_size__linux to "16" and click another list item, my value 16 is lost. is it ok?

**Comment by halfbrained** [comment]
1. it avoids accidental edits
2. replicates old plugin's behavior :)

**Comment by Alexey-T** [comment]
so I must press Enter after typing '16'? it is ok then.

**Comment by halfbrained** [comment]
> so I must press Enter after typing '16'?

Yep

**Comment by JairoMartinezA** [comment]
I am ok, I need to press Enter key to accept the modified value.

**Comment by Alexey-T** [comment]
@halfbrained so the work shoud be

- i click some option
- i click input and type smth -> you show label "mod" near the input
- i see the "mod" and press OK -> "mod" label hides
-

**Comment by JairoMartinezA** [comment]
Alex, the "mod" is about the feature discussed in #25?

If yes, I think the "mod" label will be displayed until the user press Apply or OK button.

**Comment by Alexey-T** [comment]
> I think the "mod" label will be displayed until the user press Apply or OK button.

yes, correct.
