### ISSUE TITLE
Cursor is moved to leading position after press Enter key in Filter textbox

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#24]
![image](https://user-images.githubusercontent.com/5806694/118373438-69c4a800-b57c-11eb-9921-1dcfdd596bd2.png)

After Enter key:

![image](https://user-images.githubusercontent.com/5806694/118373497-d0e25c80-b57c-11eb-9d21-61824d09008c.png)

**Comment by halfbrained** [comment]
fixed
