### ISSUE TITLE
Updated value is not refresh in Listbox control after press Enter key

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#25]
![image](https://user-images.githubusercontent.com/5806694/118373576-4e0dd180-b57d-11eb-912b-137874f82d43.png)

**Comment by halfbrained** [comment]
That is by design. It is to indicate that the value is not yet applied (it will update after hitting 'Apply').

If I to update list immediately - I would need to show a dialog on window being closed with <Escape> or OS-window-close-button (not OK, Cancel, Apply) - 'Pending option changes. Apply?' -- would this be better?

**Comment by JairoMartinezA** [comment]
What you think to put a label with "New value" caption (Close to textbox value)? And in the ListBox change "Value" to "Current value".

Again the "confusion" I think is because you are merging the ListBox functionality with a common config dialog.

**Comment by halfbrained** [comment]
Yes 'Current value' is much better, will rename.

> What you think to put a label with "New value" caption (Close to textbox value)?

I would rather not add more text, but some indication is probably needed, an icon maybe (haven't found an appropriate one yet), or maybe show it like 'edited line' state in the main editor?
![edited_val](https://user-images.githubusercontent.com/74829192/118487690-a67ed380-b723-11eb-9e98-e1322e9ff8c1.png)

**Comment by halfbrained** [comment]
icon example - this is better probably

![edited_icon](https://user-images.githubusercontent.com/74829192/118488705-b0550680-b724-11eb-8ca8-0895fb3bc5ea.png)

**Comment by Alexey-T** [comment]
Show icon when textbox is changed? ok, nice. "lite state red" is also ok.

**Comment by JairoMartinezA** [comment]
The red line is ok for me, but I suppose is only when the value is already modified, right? (Before press Apply / OK)

**Comment by halfbrained** [comment]
Added. Will show when editor value is changed or have a non-applied change for this option. 

![mod_mark](https://user-images.githubusercontent.com/74829192/118627316-472ccc00-b7d4-11eb-8f5a-250cc8d3b18a.png)

(can be easily changed if there ever a better idea)

**Comment by Alexey-T** [comment]
looks good, tkx.
