### ISSUE TITLE
@Section vs filter

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#26]
* Click en Python section, Filter textbox shows @Python.
* Click on filter textbox and change content to _arrow_ and press Enter. Options are filtered to show **scrollbar_arrows**.
* Click again in Python section, ListBox is not updated.
* Workaround, you need to press to another section and come back again to press Python section.

**Comment by halfbrained** [comment]
Clicking the same item doesn't trigger an `on_change()` event.

@Alexey-T, can an option to 'select nothing' in a tree be made? If not...

I have a few solutions, both with some problems:
1. I can use `on_click()` instead, but i has a minor drawback - it is also triggered when empty area clicked -- which will be processed as an item click - resetting filter
2. When the selected-in-tree section is removed from filter - deselect item in the tree. In absence of a proper way to deselect items in the tree I'm adding a temp item > selecting it > deleting it . The drawback here is that it is ugly :) but it works...

**Comment by Alexey-T** [comment]
Added the API to deselect in tree.

**Comment by halfbrained** [comment]
Thanks. Fixed now

... requires latest beta now though
