### ISSUE TITLE
On width resizing appears a Vertical Line

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#27]
![image](https://user-images.githubusercontent.com/5806694/118423857-95828380-b68b-11eb-9060-2bddf16b3af8.png)

**Comment by halfbrained** [comment]
This happens only occasionally. right? if so - that's probably the App's issue - and an extremely minor one - not worth fixing.

If I am mistaken - let's involve the authorities :) otherwise feel free to close
