### ISSUE TITLE
Three states for Checkbox, why not just two?

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#31]
![2021-05-19_085505](https://user-images.githubusercontent.com/5806694/118825237-20c46a80-b880-11eb-8c0a-46f6b4aa5a54.png)

**Comment by halfbrained** [comment]
Third is 'unset', analogous to this state from previous version of Option Editor:

![unset](https://user-images.githubusercontent.com/74829192/118839659-58a6ce80-b8cf-11eb-885e-065a10c06b48.png)

**Comment by Alexey-T** [comment]
@halfbrained so it's solved.

**Comment by JairoMartinezA** [comment]
My concern is, currently the textbox shows the current value even if it was modified or is the default value:

![image](https://user-images.githubusercontent.com/5806694/119003988-c8f73380-b953-11eb-9fb1-0f93f9b39484.png)

So why to do some different working with Boolean values? I think is better to show only if the value is true (Checked) or false (Unchecked)

**Comment by halfbrained** [comment]
It is actually the same: all option types, on listbox click, will show 'Current value'.

Boolean will show unchecked state *only* if you specifically choose a scope (from 'Scope' combobox) where current option is not set.

**Comment by halfbrained** [comment]
> It is actually the same: all option types, on listbox click, will show 'Current value'.
> 
> Boolean will show unchecked state _only_ if you specifically choose a scope (from 'scope' combobox) where current option is not set.

**Comment by JairoMartinezA** [comment]
I get it @halfbrained,

Comment:

The icon you are using at least for me, remember me more a status of "not-all selected" instead an *un-set* status like in this WinMerge install dialog:

![WinMerge-2 16 12-Setup tmp_2021-05-25_11-39-26](https://user-images.githubusercontent.com/5806694/119727399-d884e980-be37-11eb-9d13-d9605b0e8997.png)

Could you consider something more like the last two tiles:
![2021-05-26_001843](https://user-images.githubusercontent.com/5806694/119745782-71296280-be54-11eb-8942-146d53c03f0b.png)

![2021-05-26_184225](https://user-images.githubusercontent.com/5806694/119745807-83a39c00-be54-11eb-93a2-402fab3e4fc7.png)

SVG files only for consideration:

[icons.zip](https://github.com/halfbrained/cuda_prefs/files/6550223/icons.zip)

**Comment by halfbrained** [comment]
I'm up for a better icon, but your suggestions for me look 100% "false", and 0% "unset" :) I'll look for a better solution.

**Comment by halfbrained** [comment]
Looked around and it seems like 'dash' is frequenlty used as a third state, so I'm using it. Do these look alright?

![cbs](https://user-images.githubusercontent.com/74829192/120069885-d9648800-c090-11eb-8147-66add89cb0f0.png)


Also, if there is no objections - I will remove 'unchecked' from states when you click checkbox (will be [v] => [ ] => [v]...), and will only show it when you reset the option or choose a scope where the option is unset.

**Comment by JairoMartinezA** [comment]
Yes is ok for me in both suggestions, the icon and to use just two states.

**Comment by halfbrained** [comment]
Updated
