### ISSUE TITLE
maybe save the bottom-splitter pos?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#33]
before closing by OK
![Screenshot from 2021-05-20 19-11-40](https://user-images.githubusercontent.com/4154978/119013070-4dbb6f00-b99f-11eb-828a-adb12919455e.png)

on next call
![Screenshot from 2021-05-20 19-11-46](https://user-images.githubusercontent.com/4154978/119013226-75aad280-b99f-11eb-8d12-fcd6a58d08f0.png)

**Comment by halfbrained** [comment]
Oops, got lost after I rearranged controls. Fixed now
