### ISSUE TITLE
optiuons with note 'Note: option is global, not per-lexer.'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#34]
I can change this auto_fold_comments per -lexer! but let's disable this. it don't work per-lexer. 
![Screenshot_2021-05-24_17-26-54](https://user-images.githubusercontent.com/4154978/119362468-671d2d80-bcb5-11eb-80ff-ceac3fe652e9.png)

**Comment by halfbrained** [comment]
```
  //Note: this option is global
  //Note: option is global
```
Four options like first, but `auto_fold_comments` has the second. Easy to fix for me, but probably better to fix on your end?

**Comment by Alexey-T** [comment]
right, I must fix it.
