### ISSUE TITLE
label is not v-aligned here

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#36]
![ali](https://user-images.githubusercontent.com/4154978/124391149-d8f68700-dcf7-11eb-8ae5-2fa79fad0efe.png)

**Comment by halfbrained** [comment]
It is vertically-aligned to that `editor_combo` https://github.com/halfbrained/cuda_prefs/blob/db8b178aeeb52554583839700681d3700b30483d/dlg.py#L741

I think the text in the combo is not vertically-aligned? 

Am I supposed to add something here? https://github.com/halfbrained/cuda_prefs/blob/db8b178aeeb52554583839700681d3700b30483d/dlg.py#L725-L733

**Comment by Alexey-T** [comment]
@kvichans told me about this issue - let it be as now, not important.
