### ISSUE TITLE
TextBox content is vanished pressing End key

### ISSUE THREAD

**Issue by JairoMartinezA** [halfbrained/cuda_prefs#37]
Hi @halfbrained

I am using Windows10
![TextBoxCleaned](https://user-images.githubusercontent.com/5806694/126664782-210fbc65-b364-4255-98f3-d6b7c0172222.gif)

**Comment by halfbrained** [comment]
Good day. Not my fault :D 

Appears to be a CudaText issue, posted here https://github.com/Alexey-T/CudaText/issues/3588
