### ISSUE TITLE
too small initial window size

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#39]
init-

![Screenshot from 2021-07-27 17-01-57](https://user-images.githubusercontent.com/4154978/127167689-dbe5c329-0fc1-408b-ab3a-35b676586a1c.png)

I suggest bigger size, but not bigger than w=1024.

![Screenshot from 2021-07-27 17-02-12](https://user-images.githubusercontent.com/4154978/127167752-9d06011a-a779-4834-9bf9-b54bceb9ad7d.png)

**Comment by halfbrained** [comment]
Changed from 600x400 to 848x576 -- close to your screenshot
