### ISSUE TITLE
I suggest to change statusbar msg here

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#43]
str: `Preference: bracket_symbols [LexerHTML] .....`
![Screenshot from 2021-08-21 12-52-29](https://user-images.githubusercontent.com/4154978/130318181-168709e5-4f8b-441a-b348-cbbab55a4bcf.png)

LexerHTML ? better "lexer: HTML"
Preference? better shorter "option"

**Comment by halfbrained** [comment]
Changed
