### ISSUE TITLE
when 'section' column shown, it is too wide-- set it some smaller fixed width (in pixels)

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#6]

**Comment by halfbrained** [comment]
to mix width types I would need something like this: https://github.com/Alexey-T/CudaText/issues/3381

**Comment by halfbrained** [comment]
Config for column widths is currently read as percentages ('settings/plugin history.json' -- dlg_preferences/columns), if some columns will be fixed-width - maybe have columns in two format:
* `100` - percentage
* `100px` - fixed width in pixels

And when added - 'Section' column will have fixed-width by default

**Comment by Alexey-T** [comment]
yes, pleasee do so.

**Comment by Alexey-T** [comment]
also for column "!" set small value in pixels.

**Comment by halfbrained** [comment]
"!" should already be in pixels, 19 by default - to fit the sort-type icon, does it not work for you?

**Comment by halfbrained** [comment]
Any advice on how to choose default "Section" column pixel-width? 120 works for me, but I'm fond of small fonts, and that is probably uncommon among the programmers :)

**Comment by Alexey-T** [comment]
ok, let it be 120px. some guess.

**Comment by halfbrained** [comment]
Added, you'll need to hide, then show them to use new default width for "Section"
