### ISSUE TITLE
font on bottom is strange (Courier?)

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_prefs#7]
here ok

![Screenshot from 2021-05-09 17-52-28](https://user-images.githubusercontent.com/4154978/117576677-6bf7b400-b0ef-11eb-8655-ba9769e0ab96.png)

here not

![Screenshot from 2021-05-09 17-52-06](https://user-images.githubusercontent.com/4154978/117576683-731ec200-b0ef-11eb-93cc-85fb57c61f28.png)

**Comment by halfbrained** [comment]
If you are talking about `Editor` widgets - they are using values from options: 'font_name' and 'font_size'. Is there a more appropriate option?

After opening the dialog you can check the actual font used (in Console):
``` python
from cuda_prefs.dlg import font_name,font_size; print(font_name, font_size)
```

**Comment by Alexey-T** [comment]
under linux:
```
>>> from cuda_prefs.dlg import font_name,font_size; print(font_name, font_size)
Init: cudatext
None None
```

**Comment by Alexey-T** [comment]
when font is not configured.

**Comment by Alexey-T** [comment]
on linux I have in user.json
```
  "font_name" : "Courier New",
  "font_size" : 12,
```
but it's options for WIN.

**Comment by halfbrained** [comment]
Ok, I need to manually choose a suffixed font option from these? (I thought there was some overriding going on automatically :) )


'settings_default/default.json'
``` json
//Some options have suffix for OS:
//  Windows: empty
//  Linux:   "__linux"
//  macOS:   "__mac"
//  FreeBSD: "__freebsd"
//  OpenBSD: "__openbsd"
//  NetBSD: "__netbsd"
//  DragonFlyBSD: "__dragonfly"
//  Solaris: "__solaris"
//  Haiku: "__haiku"
```

**Comment by Alexey-T** [comment]
yes..

**Comment by halfbrained** [comment]
Widgets 'editor' and 'editor_edit' by default get different fonts+sizes, is there a reason for that or is it okay to use the same for both?

**Comment by Alexey-T** [comment]
maybe initing of both controls are different. 

>okay to use the same for both?

Ok.

**Comment by halfbrained** [comment]
Added the usual: win, mac, lin. Don't have access to the other other ones, so will add when the need arises
